push_indications:
  target:
    entity:
      integration: mosoblgaz
      device_class: gas
  fields:
    indications:
      required: true
      advanced: false
      example: '123'
      selector:
        text:
          multiline: false
    incremental:
      required: false
      advanced: false
      default: false
      example: 'false'
      selector:
        boolean:
    ignore_indications:
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:
