name: Prepare release asset

on:
  release:
    types: [prereleased,published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compress component directory
        run: |
          cd custom_components/mosoblgaz
          zip mosoblgaz.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/mosoblgaz/mosoblgaz.zip
          asset_name: mosoblgaz.zip
          tag: ${{ github.ref }}
          overwrite: true